#!/bin/bash
target=$1
shift
args=$@

path=`pwd`
while true;
do
    if [ -e $path/Makefile ];
    then
        make --directory=$path $target args="$args"
        break
    fi
    path=`dirname $path`
    
    if [ $path = `dirname $path` ];
    then
        make $target $args
        break
    fi
done

